name: models
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  mobx: ^2.3.2
  flutter_mobx: ^2.2.0+2
  equatable: ^2.0.7
  http: ^0.13.6
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.3.7
  sqflite: ^2.2.8+4
  path: ^1.8.2
  drift: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
