// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkomg3UfwjGfTSEM_ElElwlNZHa8HUtVE',
    appId: '1:1085001994671:web:3bddc902aba75fcbd7df5a',
    messagingSenderId: '1085001994671',
    projectId: 'clean-8c03f',
    authDomain: 'clean-8c03f.firebaseapp.com',
    storageBucket: 'clean-8c03f.firebasestorage.app',
    measurementId: 'G-N1JKVEWVYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLxL5UjVqNMI2Fq9XZBk0QL1XdHD6cEY',
    appId: '1:1085001994671:android:667435b88d35d18ed7df5a',
    messagingSenderId: '1085001994671',
    projectId: 'clean-8c03f',
    storageBucket: 'clean-8c03f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_uCqIQgKHI-iSr9aiDveB9cqyN4DW7E',
    appId: '1:1085001994671:ios:11877f159661527ed7df5a',
    messagingSenderId: '1085001994671',
    projectId: 'clean-8c03f',
    storageBucket: 'clean-8c03f.firebasestorage.app',
    iosBundleId: 'com.example.clean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_uCqIQgKHI-iSr9aiDveB9cqyN4DW7E',
    appId: '1:1085001994671:ios:11877f159661527ed7df5a',
    messagingSenderId: '1085001994671',
    projectId: 'clean-8c03f',
    storageBucket: 'clean-8c03f.firebasestorage.app',
    iosBundleId: 'com.example.clean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkomg3UfwjGfTSEM_ElElwlNZHa8HUtVE',
    appId: '1:1085001994671:web:d97fde921b38cb45d7df5a',
    messagingSenderId: '1085001994671',
    projectId: 'clean-8c03f',
    authDomain: 'clean-8c03f.firebaseapp.com',
    storageBucket: 'clean-8c03f.firebasestorage.app',
    measurementId: 'G-N4VFGGCEF7',
  );
}
